// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmuKlBf786fVzejyY_C6sHtQFQPuhGoM',
    appId: '1:217596690848:web:1b27524e50060d7f94e4c5',
    messagingSenderId: '217596690848',
    projectId: 'book-reserve-7667f',
    authDomain: 'book-reserve-7667f.firebaseapp.com',
    storageBucket: 'book-reserve-7667f.appspot.com',
    measurementId: 'G-ZJEBSFFQ8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78_Q5xCagezuQ-zXa-Q0nMNWzb_OnmZM',
    appId: '1:217596690848:android:d73abec136ec307594e4c5',
    messagingSenderId: '217596690848',
    projectId: 'book-reserve-7667f',
    storageBucket: 'book-reserve-7667f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1m899tZ9ba4qLLBgfVYreDBT8aOB5LU',
    appId: '1:217596690848:ios:d23905e06e50be8294e4c5',
    messagingSenderId: '217596690848',
    projectId: 'book-reserve-7667f',
    storageBucket: 'book-reserve-7667f.appspot.com',
    iosBundleId: 'com.bookreservedev.bookreserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1m899tZ9ba4qLLBgfVYreDBT8aOB5LU',
    appId: '1:217596690848:ios:d23905e06e50be8294e4c5',
    messagingSenderId: '217596690848',
    projectId: 'book-reserve-7667f',
    storageBucket: 'book-reserve-7667f.appspot.com',
    iosBundleId: 'com.bookreservedev.bookreserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTmuKlBf786fVzejyY_C6sHtQFQPuhGoM',
    appId: '1:217596690848:web:d15ad4872c04911094e4c5',
    messagingSenderId: '217596690848',
    projectId: 'book-reserve-7667f',
    authDomain: 'book-reserve-7667f.firebaseapp.com',
    storageBucket: 'book-reserve-7667f.appspot.com',
    measurementId: 'G-PPBQRPJLT2',
  );
}
